# These are supported funding model platforms

# Kàá is free, MIT-licensed, with no paid tiers or locked features.
# To accept optional donations from users who want to support development,
# uncomment and fill in whichever of these the maintainer sets up:

# github: [SojiJoro]
# ko_fi: your-ko-fi-id
# custom: ["https://example.com/donate"]
