// GENERATED from shared/yoruba-language-pack.json — do not edit by hand.
// Run `npm run generate` after changing the language pack.

import Foundation

public enum YorubaTables {
    public static let base0to10: [Int: String] = [
        0: "Òdo",
        1: "Ọ̀kan",
        2: "Méjì",
        3: "Mẹ́ta",
        4: "Mẹ́rin",
        5: "Márùn-ún",
        6: "Mẹ́fà",
        7: "Méje",
        8: "Mẹ́jọ",
        9: "Mẹ́sàn-án",
        10: "Mẹ́wàá",
    ]

    public static let tensBase: [Int: String] = [
        20: "Ogún",
        30: "Ọgbọ̀n",
        40: "Ogójì",
        50: "Àádọ́ta",
        60: "Ọgọ́ta",
        70: "Àádọ́rin",
        80: "Ọgọ́rin",
        90: "Àádọ́rùn",
        100: "Ọgọ́rùn-ún",
    ]

    public static let hundredsBase: [Int: String] = [
        100: "Ọgọ́rùn-ún",
        200: "Igba",
        300: "Ọ̀ọ́dúnrún",
        400: "Irinwó",
        500: "Ẹ̀ẹ́dẹ́gbẹ̀ta",
        600: "Ẹgbẹ̀ta",
        700: "Ẹ̀ẹ́dẹ́gbẹ̀rin",
        800: "Ẹgbẹ̀rin",
        900: "Ẹ̀ẹ́dẹ́gbẹ̀rún",
        1000: "Ẹgbẹ̀rún",
    ]

    public static let traditional0to99: [Int: String] = [
        0: "Òdo",
        1: "Ọ̀kan",
        2: "Méjì",
        3: "Mẹ́ta",
        4: "Mẹ́rin",
        5: "Márùn-ún",
        6: "Mẹ́fà",
        7: "Méje",
        8: "Mẹ́jọ",
        9: "Mẹ́sàn-án",
        10: "Mẹ́wàá",
        11: "Mọ́kànlá",
        12: "Méjìlá",
        13: "Mẹ́tàlá",
        14: "Mẹ́rìnlá",
        15: "Mẹ́ẹ̀dógún",
        16: "Mẹ́rìndínlógún",
        17: "Mẹ́tàdínlógún",
        18: "Méjìdínlógún",
        19: "Mọ́kàndínlógún",
        20: "Ogún",
        21: "Mọ́kànlélógún",
        22: "Méjìlélógún",
        23: "Mẹ́tàlélógún",
        24: "Mẹ́rìnlélógún",
        25: "Mẹ́ẹ̀dọ́gbọ̀n",
        26: "Mẹ́rìndínlọ́gbọ̀n",
        27: "Mẹ́tàdínlọ́gbọ̀n",
        28: "Méjìdínlọ́gbọ̀n",
        29: "Mọ́kàndínlọ́gbọ̀n",
        30: "Ọgbọ̀n",
        31: "Mọ́kànlélọ́gbọ̀n",
        32: "Méjìlélọ́gbọ̀n",
        33: "Mẹ́tàlélọ́gbọ̀n",
        34: "Mẹ́rìnlélọ́gbọ̀n",
        35: "Márùndínlógójì",
        36: "Mẹ́rìndínlógójì",
        37: "Mẹ́tàdínlógójì",
        38: "Méjìdínlógójì",
        39: "Mọ́kàndínlógójì",
        40: "Ogójì",
        41: "Mọ́kànlélógójì",
        42: "Méjìlélógójì",
        43: "Mẹ́tàlélógójì",
        44: "Mẹ́rìnlélógójì",
        45: "Márùndínláàádọ́ta",
        46: "Mẹ́rìndínláàádọ́ta",
        47: "Mẹ́tàdínláàádọ́ta",
        48: "Méjìdínláàádọ́ta",
        49: "Mọ́kàndínláàádọ́ta",
        50: "Àádọ́ta",
        51: "Mọ́kànléláàádọ́ta",
        52: "Méjìléláàádọ́ta",
        53: "Mẹ́tàléláàádọ́ta",
        54: "Mẹ́rìnléláàádọ́ta",
        55: "Márùndínlọ́gọ́ta",
        56: "Mẹ́rìndínlọ́gọ́ta",
        57: "Mẹ́tàdínlọ́gọ́ta",
        58: "Méjìdínlọ́gọ́ta",
        59: "Mọ́kàndínlọ́gọ́ta",
        60: "Ọgọ́ta",
        61: "Mọ́kànlélọ́gọ́ta",
        62: "Méjìlélọ́gọ́ta",
        63: "Mẹ́tàlélọ́gọ́ta",
        64: "Mẹ́rìnlélọ́gọ́ta",
        65: "Márùndínláàádọ́rin",
        66: "Mẹ́rìndínláàádọ́rin",
        67: "Mẹ́tàdínláàádọ́rin",
        68: "Méjìdínláàádọ́rin",
        69: "Mọ́kàndínláàádọ́rin",
        70: "Àádọ́rin",
        71: "Mọ́kànléláàádọ́rin",
        72: "Méjìléláàádọ́rin",
        73: "Mẹ́tàléláàádọ́rin",
        74: "Mẹ́rìnléláàádọ́rin",
        75: "Márùndínlọ́gọ́rin",
        76: "Mẹ́rìndínlọ́gọ́rin",
        77: "Mẹ́tàdínlọ́gọ́rin",
        78: "Méjìdínlọ́gọ́rin",
        79: "Mọ́kàndínlọ́gọ́rin",
        80: "Ọgọ́rin",
        81: "Mọ́kànlélọ́gọ́rin",
        82: "Méjìlélọ́gọ́rin",
        83: "Mẹ́tàlélọ́gọ́rin",
        84: "Mẹ́rìnlélọ́gọ́rin",
        85: "Márùndínláàádọ́rùn",
        86: "Mẹ́rìndínláàádọ́rùn",
        87: "Mẹ́tàdínláàádọ́rùn",
        88: "Méjìdínláàádọ́rùn",
        89: "Mọ́kàndínláàádọ́rùn",
        90: "Àádọ́rùn",
        91: "Mọ́kànléláàádọ́rùn",
        92: "Méjìléláàádọ́rùn",
        93: "Mẹ́tàléláàádọ́rùn",
        94: "Mẹ́rìnléláàádọ́rùn",
        95: "Márùndínlọ́gọ́rùn",
        96: "Mẹ́rìndínlọ́gọ́rùn",
        97: "Mẹ́tàdínlọ́gọ́rùn",
        98: "Méjìdínlọ́gọ́rùn",
        99: "Mọ́kàndínlọ́gọ́rùn",
    ]

    /// Largest first. Capped at a quintillion (10^18) — the Int64 ceiling.
    public static let scaleWords: [(value: Int, word: String)] = [
        (1000000000000000000, "Kwíntílíọ̀nù"),
        (1000000000000000, "Kwadírílíọ̀nù"),
        (1000000000000, "Tirílíọ̀nù"),
        (1000000000, "Bílíọ̀nù"),
        (1000000, "Mílíọ̀nù"),
        (1000, "Ẹgbẹ̀rún"),
    ]

    public static let classicalExact: [Int: String] = [
        2000: "Ẹgbàá",
        4000: "Ẹgbàájì",
    ]

    public static let okeValue: Int = 20000
    public static let okeWord: String = "Ọkẹ́"

    public static let ordinals1to10: [Int: String] = [
        1: "Àkọ́kọ́",
        2: "Ìkejì",
        3: "Ìkẹta",
        4: "Ìkẹrin",
        5: "Ìkarùn-ún",
        6: "Ìkẹfà",
        7: "Ìkeje",
        8: "Ìkẹjọ",
        9: "Ìkẹsàn-án",
        10: "Ìkẹwàá",
    ]

    public static let particles: [String: String] = [
        "addJoin": "ó lé",
        "subtractJoin": "ó dín",
        "modernJoin": "àti",
        "decimalMark": "ààmì",
        "negative": "Òdì",
        "positive": "Àfikún",
        "one": "kan",
        "powerOfTenPhrase": "ìgbà mẹ́wàá ní ọ̀nà",
        "naira": "náírà",
        "kobo": "kọ́bọ̀",
        "ordinalFallbackPrefix": "Ipò",
    ]

    public static let operatorWords: [String: String] = [
        "+": "pẹ̀lú",
        "-": "yọ",
        "×": "ìgbà",
        "÷": "pín sí",
        "^": "ní ọ̀nà",
        "=": "dọ́gba",
    ]
}
